### ISSUE TITLE
sentence-transformers

### ISSUE THREAD

**Issue by luweishuang** [PolyAI-LDN/polyai-models#40]
I have a question, maybe stupid, I can't understand why you using "context" + "response" sentences combination format to train a sentence representation,  otherwise using similarity sentence pairs.  like [https://github.com/UKPLab/sentence-transformers](sentence-transformers) did.  Is there any benefit to do in this way or just QA dataset is more large and easy to get than similarity sentences pairs.  

 I want to train a model like ConveRT in another language and I don't have too much QA corqus in my language. I want to know could I use sentence-transformers instead to realise a conversational representations by finetune bert in a not large QA corpus?

**Comment by matthen** [comment]
We're interested in conversational AI applications, like task oriented dialogue systems. We find that models pre-trained on response ranking perform better on such tasks - see e.g. [https://www.aclweb.org/anthology/2020.nlp4convai-1.5/](Efficient Intent Detection with Dual Sentence Encoders) and [https://www.aclweb.org/anthology/2020.acl-main.11/](Span-ConveRT: Few-shot Span Extraction for Dialog with Pretrained Conversational Representations). Partly it is because it is a more conversational task, but it is also because we can use Reddit as training, with its billions of comments.

For new languages, it is hard to find a corpus as useful as Reddit for this kind of pre-training. For the [Multilingual USE](https://arxiv.org/abs/1907.04307) model, the authors actually translated parts of Reddit to various languages.

**Comment by luweishuang** [comment]
Tanks for your reply. I have a another question, I tried to collect conversation corpus in my language and I found in many screen the dialoguage goes like this:
person A: 1********
person B: 2*****
person A: 3************
person C: 4********
person B: 5*****
person D: 6**********
maybe more than two person involved in a dialoage and in such a screen, Can I use "Multi-context ConveRT" to model the dialogue just like two person screen do? Or need I do something else to this,  thanks !

**Comment by matthen** [comment]
The multi context ConveRT does not use the author of the message as a feature, in part to make it more general and not too specific to the Reddit data. It would be able to rank responses for multispeaker dialogues like this (that is how it is trained). If you are fine-tuning or recreating the model from scratch, then you could of course add the author as an extra feature when creating the context features.
